### ISSUE TITLE
Image Update

### ISSUE THREAD

**Issue by rkaunismaa** [Denis2054/Transformers-for-NLP-and-Computer-Vision-3rd-Edition#1]
In the notebook Chapter06/KantaiBERT.ipynb, in cell 30, the code attempts to reference a non existing image.

display(get_image_from_github('B17948_06_05.png') or print('Image not found'))

I think this line needs to point to ...

display(get_image_from_github('B19899_06_05.png') or print('Image not found'))

**Comment by Denis2054** [comment]
Thanks. 
You were right. The path is:
display(get_image_from_github('B19899_06_05.png').  




I just corrected the path as you pointed out, and ran the notebook.
